version: '3'
services:
  cuda-cont:
    build: .
    image: har-cont
    container_name: har-cont
    ports:
      - "5000:5000"
      - "8000:8000"
      - "42424:42424"
      - "4200:4200"
    devices:
      - "/dev/video0:/dev/video0"

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs 

  